// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

uint64_t r[2] = {0xffffffffffffffff, 0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  const char* reason;
  (void)reason;
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  *(uint32_t*)0x200003c0 = 2;
  *(uint32_t*)0x200003c4 = 0x80;
  *(uint8_t*)0x200003c8 = 0xe7;
  *(uint8_t*)0x200003c9 = 0;
  *(uint8_t*)0x200003ca = 0;
  *(uint8_t*)0x200003cb = 0;
  *(uint32_t*)0x200003cc = 0;
  *(uint64_t*)0x200003d0 = 1;
  *(uint64_t*)0x200003d8 = 0x44c21d;
  *(uint64_t*)0x200003e0 = 0;
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 0, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 1, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 2, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 3, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 4, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 5, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 6, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 7, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 8, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 9, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 10, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 11, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 12, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 13, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 14, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 15, 2);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 17, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 18, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 19, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 20, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 21, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 22, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 23, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 24, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 25, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 26, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 27, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 28, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 29, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 30, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 31, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 32, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 33, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 34, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 35, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 36, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 37, 1);
  STORE_BY_BITMASK(uint64_t, , 0x200003e8, 0, 38, 26);
  *(uint32_t*)0x200003f0 = 0x203;
  *(uint32_t*)0x200003f4 = 0;
  *(uint64_t*)0x200003f8 = 0x202ece72;
  *(uint64_t*)0x20000400 = 0xfffffffffffffe05;
  *(uint64_t*)0x20000408 = 0x2802;
  *(uint64_t*)0x20000410 = 3;
  *(uint32_t*)0x20000418 = 0x91;
  *(uint32_t*)0x2000041c = 6;
  *(uint64_t*)0x20000420 = 8;
  *(uint32_t*)0x20000428 = 0;
  *(uint16_t*)0x2000042c = 0;
  *(uint16_t*)0x2000042e = 0;
  *(uint32_t*)0x20000430 = 0;
  *(uint32_t*)0x20000434 = 0;
  *(uint64_t*)0x20000438 = 0x14;
  syscall(__NR_perf_event_open, /*attr=*/0x200003c0ul, /*pid=*/0, /*cpu=*/-1,
          /*group=*/-1, /*flags=*/0ul);
  for (int i = 0; i < 64; i++) {
    syscall(__NR_perf_event_open, /*attr=*/0x200003c0ul, /*pid=*/0, /*cpu=*/-1,
            /*group=*/-1, /*flags=*/0ul);
  }
  res = syscall(__NR_socket, /*domain=*/0x18ul, /*type=*/1ul, /*proto=*/0);
  for (int i = 0; i < 64; i++) {
    syscall(__NR_socket, /*domain=*/0x18ul, /*type=*/1ul, /*proto=*/0);
  }
  if (res != -1)
    r[0] = res;
  *(uint16_t*)0x20000400 = 0x18;
  *(uint32_t*)0x20000402 = 0;
  *(uint16_t*)0x20000406 = 2;
  memset((void*)0x20000408, 170, 5);
  *(uint8_t*)0x2000040d = 0xa;
  memcpy((void*)0x2000040e,
         "lo\000\000\000\000\000\000\000\000\000\000\000\000\000\000", 16);
  syscall(__NR_connect, /*fd=*/r[0], /*addr=*/0x20000400ul, /*addrlen=*/0x1eul);
  res = syscall(__NR_socket, /*domain=*/0x10ul, /*type=*/3ul, /*proto=*/0x14);
  if (res != -1)
    r[1] = res;
  memcpy((void*)0x20000280, "/dev/infiniband/rdma_cm\000", 24);
  syscall(__NR_openat, /*fd=*/0xffffffffffffff9cul, /*file=*/0x20000280ul,
          /*flags=*/2, /*mode=*/0);
  *(uint64_t*)0x20000440 = 0;
  *(uint32_t*)0x20000448 = 0;
  *(uint64_t*)0x20000450 = 0x20000400;
  *(uint64_t*)0x20000400 = 0x20000280;
  memcpy((void*)0x20000280, "\x38\x00\x00\x00\x14\x14\x01", 7);
  *(uint64_t*)0x20000408 = 0x38;
  *(uint64_t*)0x20000458 = 1;
  *(uint64_t*)0x20000460 = 0;
  *(uint64_t*)0x20000468 = 0;
  *(uint32_t*)0x20000470 = 0x4000;
  syscall(__NR_sendmsg, /*fd=*/r[1], /*msg=*/0x20000440ul,
          /*f=MSG_PROBE*/ 0x10ul);
  syscall(__NR_ioctl, /*fd=*/r[0], /*cmd=*/0x80047437, /*arg=*/0x20001f00ul);
  return 0;
}
