// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

uint64_t r[1] = {0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  const char* reason;
  (void)reason;
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  memcpy((void*)0x20000500, "/dev/sequencer2\000", 16);
  res = syscall(__NR_openat, /*fd=*/0xffffffffffffff9cul, /*file=*/0x20000500ul,
                /*flags=O_WRONLY*/ 1, /*mode=*/0);
  if (res != -1)
    r[0] = res;
  memcpy((void*)0x20000540, "\x94\x04\x39\x54", 4);
  syscall(__NR_write, /*fd=*/r[0], /*buffer=*/0x20000540ul, /*count=*/0x1dul);
  for (int i = 0; i < 64; i++) {
    syscall(__NR_write, /*fd=*/r[0], /*buffer=*/0x20000540ul, /*count=*/0x1dul);
  }
  memcpy(
      (void*)0x20000140,
      "\x94\x04\xab\x3f\x86\xf5\xda\xd6\x5c\xf3\x89\xf7\xd6\xf3\xd7\x89\xad\x31"
      "\x2d\xf7\xe8\x36\x33\xf4\xa0\x5f\x37\x93\x6b\x28\xcf\xc9\x93\x7e\x46\x1f"
      "\xf1\xfc\xe0\x26\x7e\x6e\x92\xa7\xd9\x03\xcc\x2a\x4b\xae\x11\x4c\xe0\x18"
      "\x70\x7c\xa2\x05\x00\x6a\x12\x46\xfa\xaa\xde\xbb\xe3\xb1\xa1\x83\x9e\x7e"
      "\x3e\xe9\x16\x92\x95\xf2\x33\xaa\x2d\xba\xcf\x2b\x7b\xbd\xe1\x20\xac\xc5"
      "\xe4\x71\xa9\x1b\xf1\x70\x04\x23\x2a\x20\x64\x1f\xa8\xf6\x98\x4a\x74\x67"
      "\x88\xc2\x5e\x8a\x4e\x6e\xc2\xc2\xe7\x5c\x5f\x0c\x02\x00\x00\x00\x00\x00"
      "\x00\x00\xda\x92\xeb\x07\x4d\xe0\xce\x37\x50\xcb\x7c\x13\x8d\xf4\x70\x32"
      "\x69\xcb\x42\x76\x39\x69\xb0\x1d\x9a\x19\x6f\x44\x9d\x34\xfd\xdb\xc4\x4a"
      "\xe4\x29\x1e\x6c\xa0\x24\x13\x60\xfc\xa1\x57\x9d\xce\x30\xb8\x97\x22\x06"
      "\xcd\x30\x01\x6b\xaf\x96\x1d\xd8\x05\x95\xdf\x83\xb9\x68\x76\x86\x5d\x89"
      "\x5b\x25\x82\xef\x04\x9d\xf3\x9c\xb3\xb0\xe6\x66\x4a\x7b\xdf\x2b\x3f\x69"
      "\xc6\x04\xa9\x8b\xb9\xf7\x34\xde\x33\x47\x93\x67\x09\xa2\x7d\x8a\x34\xc5"
      "\x89\xbd\x72\x6e\xaf\xee\x7e\x13\x8f\x4a\x6c\xc6\x89\xf6\xff\x69\x6f\x79"
      "\xc0\xda\x26\x73\xf2\xa0\xb1\x31\x29\xea\xee\x1e\xb0\x8e\xae\xf1\x44\xcd"
      "\x15\xb6\x78\xa5\xde\xb5\x14\x1d\x23\x1d\xbb\x99\xfb\xbd\x35\x95\x8e\x5c"
      "\xf8\xb2",
      290);
  syscall(__NR_write, /*fd=*/r[0], /*buffer=*/0x20000140ul, /*count=*/8ul);
  for (int i = 0; i < 64; i++) {
    syscall(__NR_write, /*fd=*/r[0], /*buffer=*/0x20000140ul, /*count=*/8ul);
  }
  return 0;
}
