// autogenerated by syzkaller (https://github.com/google/syzkaller)

#define _GNU_SOURCE

#include <endian.h>
#include <sched.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <unistd.h>

#define BITMASK(bf_off, bf_len) (((1ull << (bf_len)) - 1) << (bf_off))
#define STORE_BY_BITMASK(type, htobe, addr, val, bf_off, bf_len)               \
  *(type*)(addr) =                                                             \
      htobe((htobe(*(type*)(addr)) & ~BITMASK((bf_off), (bf_len))) |           \
            (((type)(val) << (bf_off)) & BITMASK((bf_off), (bf_len))))

#define USLEEP_FORKED_CHILD (3 * 50 * 1000)

static long handle_clone_ret(long ret)
{
  if (ret != 0) {
    return ret;
  }
  usleep(USLEEP_FORKED_CHILD);
  syscall(__NR_exit, 0);
  while (1) {
  }
}

static long syz_clone(volatile long flags, volatile long stack,
                      volatile long stack_len, volatile long ptid,
                      volatile long ctid, volatile long tls)
{
  long sp = (stack + stack_len) & ~15;
  long ret = (long)syscall(__NR_clone, flags & ~CLONE_VM, sp, ptid, ctid, tls);
  return handle_clone_ret(ret);
}

uint64_t r[2] = {0x0, 0xffffffffffffffff};

int main(void)
{
  syscall(__NR_mmap, /*addr=*/0x1ffff000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0x1000000ul,
          /*prot=PROT_WRITE|PROT_READ|PROT_EXEC*/ 7ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  syscall(__NR_mmap, /*addr=*/0x21000000ul, /*len=*/0x1000ul, /*prot=*/0ul,
          /*flags=MAP_FIXED|MAP_ANONYMOUS|MAP_PRIVATE*/ 0x32ul, /*fd=*/-1,
          /*offset=*/0ul);
  const char* reason;
  (void)reason;
  intptr_t res = 0;
  if (write(1, "executing program\n", sizeof("executing program\n") - 1)) {
  }
  STORE_BY_BITMASK(uint8_t, , 0x20000600, 1, 0, 7);
  STORE_BY_BITMASK(uint8_t, , 0x20000600, 1, 7, 1);
  syscall(__NR_ioctl, /*fd=*/-1, /*cmd=*/0x80045503, /*arg=*/0x20000600ul);
  syscall(__NR_fcntl, /*fd=*/-1, /*cmd=*/0xful, /*arg=*/0ul);
  res = -1;
  res = syz_clone(/*flags=*/0, /*stack=*/0, /*stack_len=*/0, /*parentid=*/0,
                  /*childtid=*/0, /*tls=*/0);
  if (res != -1)
    r[0] = res;
  syscall(__NR_ptrace, /*req=PTRACE_ATTACH*/ 0x10ul, /*pid=*/r[0], 0, 0);
  memcpy((void*)0x20000040, "cgroup.freeze\000", 14);
  res = syscall(__NR_openat, /*fd=*/0xffffff9c, /*file=*/0x20000040ul,
                /*flags=*/0x275a, /*mode=*/0);
  if (res != -1)
    r[1] = res;
  memcpy((void*)0x20000280, "#! ", 3);
  *(uint8_t*)0x20000283 = 0xa;
  syscall(__NR_write, /*fd=*/r[1], /*data=*/0x20000280ul, /*len=*/0x208e24bul);
  syscall(__NR_mmap, /*addr=*/0x20000000ul, /*len=*/0xb36000ul,
          /*prot=PROT_GROWSDOWN|PROT_WRITE|PROT_READ*/ 0x1000003ul,
          /*flags=MAP_STACK|MAP_POPULATE|MAP_FIXED|MAP_SHARED*/ 0x28011ul,
          /*fd=*/r[1], /*offset=*/0ul);
  syscall(__NR_prlimit64, /*pid=*/0, /*res=RLIMIT_NOFILE*/ 7ul, /*new=*/0ul,
          /*old=*/0ul);
  *(uint64_t*)0x20000240 = 0x20000180;
  *(uint64_t*)0x20000248 = 0xffffffffffffff28;
  syscall(__NR_ptrace, /*req=*/0x4205ul, /*pid=*/r[0],
          /*what=NT_X86_XSTATE*/ 0x202ul, /*data=*/0x20000240ul);
  *(uint32_t*)0x20000100 = 0x200;
  *(uint32_t*)0x20000104 = 0x100;
  STORE_BY_BITMASK(uint32_t, , 0x20000108, 0, 0, 1);
  memcpy((void*)0x20000109,
         "queue1\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
         "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
         "\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000"
         "\000\000\000\000\000\000\000\000\000",
         64);
  *(uint32_t*)0x2000014c = 5;
  memset((void*)0x20000150, 0, 60);
  syscall(__NR_ioctl, /*fd=*/-1, /*cmd=*/0x408c5333, /*arg=*/0x20000100ul);
  return 0;
}
